version: 2.1

executors:
  sgrep-build:
    docker:
      - image: returntocorp/sgrep-build:2.5

jobs:
  build:
    executor: sgrep-build
    steps:
      - checkout
      - run: pip3 install -r requirements.txt
      - run: cd ~ && git clone  https://github.com/returntocorp/pfff
      - run: eval $(opam env) && cd ~/pfff && ./configure && make depend && make && make opt && make install-libs
      - run: eval $(opam env); make all
      - persist_to_workspace:
          root: /home/opam/project
          paths:
            - _build
  test:
    executor: sgrep-build
    steps:
      - checkout
      - attach_workspace:
          at: /home/opam/project
      - run: ln -s /home/opam/project/_build/default/bin/main_sgrep.exe /home/opam/.local/bin/sgrep
      - run: pip3 install -r requirements.txt
      - run: cd ~ && git clone  https://github.com/returntocorp/pfff # TODO remove and just mount these two lines
      - run: eval $(opam env) && cd ~/pfff && ./configure && make depend && make && make opt && make install-libs
      - run: eval $(opam env); make test

  publish_mac:
    macos:
      xcode: 11.3.1
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: brew install ghr
      - run: brew install opam
      - run: opam init --no-setup --bare
      - run: opam switch create 4.07.1
      - run: opam switch 4.07.1
      - run: eval $(opam env); opam install reason dune ocamlfind camlp4 num ocamlgraph json-wheel conf-perl yaml
      - run: cd ~; git clone https://github.com/returntocorp/pfff
      - run: eval $(opam env); cd ~/pfff; ./configure; make depend; make; make opt; make reinstall-libs
      - run: eval $(opam env); cd ~/project; dune build
      - run: ls -la **/*
      - run: ~/project/_build/default/bin/main_sgrep.exe -help
      - run: ghr --help
      - run: ghr -replace latest-dev ~/project/_build/default/bin/main_sgrep.exe

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - publish_mac
      - build
      - test:
          requires:
            - build
