on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Validate a release

jobs:
  sanity_check_release:
    name: Sanity check the release
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Install JQ
        run: sudo apt-get update && sudo apt install -y jq
      - name: Download release info
        #run: curl https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.get_version.outputs.VERSION }} > release.json
        run: curl https://api.github.com/repos/returntocorp/sgrep/releases/latest > release.json
      - name: Verify something that looks like release notes
        run: cat release.json | jq '.body' | grep "Changed"
      - name: Save release name to a file
        run: cat release.json | jq '.tag_name' > version
      - name: Verify ubuntu binary exists
        run: cat release.json | jq '.assets[].name' | grep "sgrep-$(cat version)-ubuntu-16.04.tgz"
