on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Validate a release

jobs:
  sanity_check_release:
    name: Sanity check the release
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Verify release exists
        run: curl https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.VERSION }} 
